#myset={'a','b'}
#print(myset)
#c=myset.add((5,4))
#print(c)
a,b = (int(input()),input().split())
c,d = (int(input()),input().split())
x=set(b)
y=set(d)
i=x.difference(y)
j=y.difference(x)
k=i.union(j)
#print(i)
#print(j)
#print(k)
print('\n'.join(sorted(k)))
